"""add fire_damage to player_match_stats

Revision ID: 00d948669318
Revises: 68d817e6fee3
Create Date: 2026-06-27 14:30:52.437807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d948669318'
down_revision: Union[str, None] = '68d817e6fee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_match_stats', sa.Column('fire_damage', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_match_stats', 'fire_damage')
    # ### end Alembic commands ###
