"""add display_name and avatar_url to players

Revision ID: 0f4cb0768353
Revises: e66cba14a98d
Create Date: 2026-06-28 03:12:51.683061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4cb0768353'
down_revision: Union[str, None] = 'e66cba14a98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('players', sa.Column('display_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'display_name')
    op.drop_column('players', 'avatar_url')
    # ### end Alembic commands ###
