"""remove ranking_config

Revision ID: 68d817e6fee3
Revises: 8c264163dd4b
Create Date: 2026-06-25 22:13:35.635049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68d817e6fee3'
down_revision: Union[str, None] = '8c264163dd4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ranking_config_id', table_name='ranking_config')
    op.drop_table('ranking_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('weight_combat', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('weight_duel', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('weight_utility', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['players.id'], name='ranking_config_updated_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='ranking_config_pkey')
    )
    op.create_index('ix_ranking_config_id', 'ranking_config', ['id'], unique=False)
    # ### end Alembic commands ###
