"""add_mvps_to_player_match_stats

Revision ID: c6e87ec82e1d
Revises: e80dd8bf709b
Create Date: 2026-06-29 20:56:27.161647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e87ec82e1d'
down_revision: Union[str, None] = 'e80dd8bf709b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default necessário: tabela já tem linhas (partidas existentes)
    op.add_column('player_match_stats', sa.Column('mvps', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_match_stats', 'mvps')
    # ### end Alembic commands ###
