"""add player_vs_player_stats table

Revision ID: e66cba14a98d
Revises: 00d948669318
Create Date: 2026-06-27 15:45:40.623991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66cba14a98d'
down_revision: Union[str, None] = '00d948669318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_vs_player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('flash_assists', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opponent_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', 'opponent_id', name='uq_match_player_opponent')
    )
    op.create_index(op.f('ix_player_vs_player_stats_id'), 'player_vs_player_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_vs_player_stats_match_id'), 'player_vs_player_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_player_vs_player_stats_opponent_id'), 'player_vs_player_stats', ['opponent_id'], unique=False)
    op.create_index(op.f('ix_player_vs_player_stats_player_id'), 'player_vs_player_stats', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_vs_player_stats_player_id'), table_name='player_vs_player_stats')
    op.drop_index(op.f('ix_player_vs_player_stats_opponent_id'), table_name='player_vs_player_stats')
    op.drop_index(op.f('ix_player_vs_player_stats_match_id'), table_name='player_vs_player_stats')
    op.drop_index(op.f('ix_player_vs_player_stats_id'), table_name='player_vs_player_stats')
    op.drop_table('player_vs_player_stats')
    # ### end Alembic commands ###
