"""add opening_deaths to player_match_stats

Revision ID: e80dd8bf709b
Revises: 43cbbcd23a39
Create Date: 2026-06-28 23:46:58.699219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80dd8bf709b'
down_revision: Union[str, None] = '43cbbcd23a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='0' necessário: tabela já tem linhas (partidas existentes)
    op.add_column('player_match_stats', sa.Column('opening_deaths', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_match_stats', 'opening_deaths')
    # ### end Alembic commands ###
